---
# tasks file for nginx
- name: install nginx on the webserver
  apt:
      name: nginx
      state: present


- name: ensure nginx is started and enabled
  service:
     name: nginx
     state: started 
     enabled: true

- name: install PHP
  apt:
    name:
      - php 
      - php-mysqlnd
      - php-gd 
      - php-curl
    state: present
