plugin: amazon.aws.aws_ec2
aws_profile: default

regions:
  - "us-east-2"

strict: False

keyed_groups:
- key: tags
  prefix: tag

filters:
  tag:Name:
    - yheancarh-bastion
    - yheancarh-nginx
    - yheancarh-tooling
    - yheancarh-wordpress
    - Yheancarh-sonarqube
    - Yheancarh-artifactory
    - Yheancarh-Jenkins
  instance-state-name : running
  
hostnames:
# a list in order of precedence for hostname variables.
  - private-ip-address
  - tag:Name
  - dns-name
  - ip-address

compose:
  ansible_host: private_ip_address



 