- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-2022061622244065030000000c.cvqm1hu6ijyh.us-east-2.rds.amazonaws.com"
    login_user: "yheancarh"
    login_password: "dm!n1234"
    name: wordpressdb
    collation: utf8_general_ci
    encoding: utf8
    state: present


- name: Input wordpress credentials
  ansible.builtin.replace:
    path: /var/www/html/wp-config.php 
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^localhost', line: "terraform-2022061622244065030000000c.cvqm1hu6ijyh.us-east-2.rds.amazonaws.com" }
    - { regexp: '^username_here', line: "yheancarh" }
    - { regexp: '^database_name_here', line: "wordpressdb" }
    - { regexp: '^password_here', line: "dm!n1234" }
