---
# tasks file for webserver
- name: Install Apache
  become: true
  yum: 
    name: httpd
    state: present
  
- name: Install git
  become: true
  yum:
    name: git
    state: present

- name: Clone a Repo
  become: true
  git:
    repo: https://github.com/Horleryheancarh/tooling.git
    dest: /var/www/html
    force: true

- name: Copy html content one level up
  become: true
  command: cp -r /var/www/html/html /var/www/

- name: Start httpd if not started
  become: true
  service: 
    name: httpd
    state: started

- name: Recursively remove /var/www/html/html directory
  become: true
  file: 
    path: /var/www/html/html
    state: absent

