---
- name: Include dynamic variables
  hosts: all
  import_playbook: ../static-assignments/common-del.yml
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always


- hosts: uat-webservers
  import_playbook: ../static-assignments/uat-webservers.yml
